spring:
  h2:
    console:
      enabled: true

  r2dbc:
    url: r2dbc:h2:mem:///demo?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.data.r2dbc: DEBUG
  config: classpath:logback-spring.xml

---
spring:
  profiles: dev

logging:
  file:
    name: demo.log
  level:
    root: INFO
    org.springframework.security: DEBUG
  config: classpath:logback-dev.xml

