server:
    port: 8081

spring:
    application:
        name: taco-service
    boot:
        admin:
            client:
                url: http://localhost:9090
                instance:
                    metadata:
                        user.name: admin
                        user.password: password

    cloud:
        config:
            uri: http://localhost:8888

management:
    endpoints:
        web:
            exposure:
                include: '*'
                exclude: threaddump, heapdump
    endpoint:
        health:
            show-details: always
    info:
        git:
            mode: full

info:
    contact:
        email: support@tacocloud.com
        phone: 822-625-6831