version: '2.1'

services:
    # https://github.com/thelastpickle/docker-cassandra-bootstrap/blob/master/docker-compose.yml
    cassandra:
        image: cassandra
        container_name: cassandra1
        env_file:
            - cassandra.env
        ports:
            - 9042:9042
        volumes:
            - ./data/cassandra:/var/lib/cassandra