spring:
    application:
        name: ingredient-client

    cloud:
        config:
            uri: http://localhost:8888

management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream