server:
    port: 8082

spring:
    application:
        name: ingredient-client

    cloud:
        config:
            uri: http://localhost:8888

management:
    endpoints:
        web:
            exposure:
                include: '*'
                exclude: threaddump, heapdump
    endpoint:
        health:
            show-details: always
    info:
        git:
            mode: full

info:
    contact:
        email: support@tacocloud.com
        phone: 822-625-6831