spring:
  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: sa
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

---

logging:
  file: demo.log
  level:
    root: INFO
    org.springframework.security: DEBUG
